apiVersion: apps/v1
kind: Deployment
metadata:
  name: memory-game-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memory-game
  template:
    metadata:
      labels:
        app: memory-game
    spec:
      containers:
      - name: memory-game
        image: wober01/memory-game:latest  
        ports:
        - containerPort: 80
